apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: carts-db
  template:
    metadata:
      labels:
        name: carts-db
    spec:
      containers:
      - name: carts-db
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /data/db
          name: cart-db-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: cart-db-volume
          persistentVolumeClaim:
           claimName: cart-db-volume-claim
      nodeSelector:
        beta.kubernetes.io/os: linux
