apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 17Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-db
  template:
    metadata:
      labels:
        name: user-db
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
      - name: init-myservice
        securityContext:
          runAsUser: 999
        image: weaveworksdemos/user-db:0.3.0
        command: ["/bin/sh"]
        args: ["-c", "cp -R /data/db-users/* /data/tmp/"] 
        volumeMounts:
        - mountPath: /data/tmp
          name: users-db-volume
      containers:
      - name: user-db
        image: weaveworksdemos/user-db:0.3.0
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        #- mountPath: /tmp
        #  name: tmp-volume
        - mountPath: /data/db-users
          name: users-db-volume
        #- mountPath: /data
        #  name: tmp-volume2
      volumes:
        #- name: tmp-volume
        #  emptyDir:
        #    medium: Memory
        #- name: tmp-volume2
        #  emptyDir:
        #    medium: Memory
        - name: users-db-volume
          persistentVolumeClaim:
            claimName: users-db-volume-claim
      nodeSelector:
        beta.kubernetes.io/os: linux
